name: Build Modded Fishing

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: chmod +x gradlew
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: moddedfishing-1.0.0
          path: build/libs/moddedfishing-1.0.0.jar
          retention-days: 30
